// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateTickets implements pgx.CopyFromSource.
type iteratorForCreateTickets struct {
	rows                 []CreateTicketsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTickets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTickets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].EventID,
	}, nil
}

func (r iteratorForCreateTickets) Err() error {
	return nil
}

func (q *Queries) CreateTickets(ctx context.Context, arg []CreateTicketsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tickets"}, []string{"id", "event_id"}, &iteratorForCreateTickets{rows: arg})
}
