// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bookTickets = `-- name: BookTickets :exec
UPDATE tickets SET user_id = $1, status = 'booked' WHERE id = ANY($2::uuid[])
`

type BookTicketsParams struct {
	UserID  pgtype.UUID
	Column2 []pgtype.UUID
}

func (q *Queries) BookTickets(ctx context.Context, arg BookTicketsParams) error {
	_, err := q.db.Exec(ctx, bookTickets, arg.UserID, arg.Column2)
	return err
}

type CreateTicketsParams struct {
	ID      pgtype.UUID
	EventID pgtype.UUID
}

const getAvailableTickets = `-- name: GetAvailableTickets :many
SELECT id FROM tickets WHERE event_id = $1 AND status = 'available'
`

func (q *Queries) GetAvailableTickets(ctx context.Context, eventID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAvailableTickets, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
