// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateTicketsParams struct {
	ID      pgtype.UUID
	EventID pgtype.UUID
}
